# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[git_status]
style="bold green"
conflicted="[!](red)"
staged="[+](yellow)"

# Hide some symbols
deleted=""
renamed=""
untracked=""
