# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
fish_style_pwd_dir_length=30

[git_branch]
format="[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style="bold green"
conflicted="[!](red)"
staged="[+](yellow)"

# Hide some symbols
deleted=""
renamed=""
untracked=""

[cmd_duration]
format="[($duration)](yellow)"
